// src/generator/index.ts
import type { DFA, LexSpec } from '../types.js';

export interface GenerateOptions {
    compressTables: boolean;
    debug: boolean;
    functionName: string;
    filename: string;
}

export interface GeneratedCode {
    header: string;
    transitionTable: string;
    acceptTable: string;
    lexerFunction: string;
    actions: string;
    trailer: string;
}

const DEFAULT_OPTIONS: GenerateOptions = {
    compressTables: false,
    debug: false,
    functionName: 'yylex',
    filename: 'lex.yy.c'
};

export async function generate(
    dfa: DFA,
    spec: LexSpec,
    outputFile: string
): Promise<void> {
    const code = generateToString(dfa, spec);
    const { writeFile } = await import('fs/promises');
    await writeFile(outputFile, code);
}

export function generateToString(dfa: DFA, spec: LexSpec): string {
    const parts = generateParts(dfa, spec);

    return `/* Generated by SeuLex */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ===== User Header ===== */
${parts.header}

/* ===== Definitions ===== */
#define YY_NUM_STATES ${dfa.states.length}
#define YY_NUM_RULES ${spec.rules.length}

/* ===== Tables ===== */
${parts.transitionTable}

${parts.acceptTable}

/* ===== Global Variables ===== */
char *yytext = NULL;
int yyleng = 0;
FILE *yyin = NULL;
static char yy_buffer[8192];
static char *yy_buf_pos = yy_buffer;
static int yy_buf_end = 0;
static int yy_buf_filled = 0;

/* ===== Helper Functions ===== */
static int yy_getchar(void) {
    if (!yyin) yyin = stdin;

    if (yy_buf_pos >= yy_buffer + yy_buf_end) {
        yy_buf_end = fread(yy_buffer, 1, sizeof(yy_buffer), yyin);
        yy_buf_pos = yy_buffer;
        yy_buf_filled = yy_buf_end;
        if (yy_buf_end == 0) return EOF;
    }
    return (unsigned char)*yy_buf_pos++;
}

static void yy_ungetchar(void) {
    if (yy_buf_pos > yy_buffer) yy_buf_pos--;
}

static int yy_at_eof(void) {
    return yy_buf_filled == 0;
}

/* ===== Lexer Function ===== */
int yylex(void) {
    int state = ${dfa.startStateId};
    char *start = yy_buf_pos;
    int last_accept_pos = -1;
    int last_accept_state = -1;

    if (!yyin) yyin = stdin;

    while (1) {
        int c = yy_getchar();
        int next = (c == EOF) ? -1 : yy_next[state][(unsigned char)c];

        if (next == -1) {
            /* 无转移，回退到最近接受状态 */
            if (last_accept_state != -1) {
                /* 回退到接受位置 */
                while (yy_buf_pos > yy_buffer + last_accept_pos) {
                    yy_ungetchar();
                }
                yyleng = last_accept_pos - (start - yy_buffer);
                yytext = malloc(yyleng + 1);
                memcpy(yytext, start, yyleng);
                yytext[yyleng] = '\\0';

                switch (yy_accept[last_accept_state]) {
${parts.actions}
                    default: return 0;
                }
            } else if (c == EOF) {
                return 0; /* EOF */
            } else {
                /* 错误：无法识别的字符 */
                fprintf(stderr, "Error: unexpected character '\\%c'\\n", c);
                return -1;
            }
        }

        if (yy_accept[next]) {
            last_accept_state = next;
            last_accept_pos = yy_buf_pos - yy_buffer;
        }

        state = next;
    }
}

/* ===== User Code ===== */
${parts.trailer}
`;
}

export function generateParts(dfa: DFA, spec: LexSpec): GeneratedCode {
    return {
        header: spec.header,
        transitionTable: generateTransitionTable(dfa),
        acceptTable: generateAcceptTable(dfa),
        lexerFunction: '', // 在主生成函数中内联
        actions: generateActions(spec),
        trailer: spec.trailer
    };
}

function generateTransitionTable(dfa: DFA): string {
    const lines: string[] = [];
    lines.push('static const int yy_next[' + dfa.states.length + '][256] = {');

    for (const state of dfa.states) {
        const trans: string[] = [];
        for (let c = 0; c < 256; c++) {
            trans.push(state.transitions[c].toString());
        }

        // 将 256 个值分成多行
        const rowValues: string[] = [];
        for (let i = 0; i < 256; i += 16) {
            const chunk = trans.slice(i, i + 16);
            rowValues.push(chunk.join(', '));
        }

        lines.push('    {');
        for (const row of rowValues) {
            lines.push('        ' + row + ',');
        }
        lines.push('    },');
    }

    lines.push('};');
    return lines.join('\n');
}

function generateAcceptTable(dfa: DFA): string {
    const accepts = dfa.states.map(s => s.acceptRule + 1); // 0 表示不接受
    return `static const int yy_accept[${dfa.states.length}] = { ${accepts.join(', ')} };`;
}

function generateActions(spec: LexSpec): string {
    const lines: string[] = [];

    for (let i = 0; i < spec.rules.length; i++) {
        lines.push(`                    case ${i + 1}:`);
        lines.push(`                        ${spec.rules[i].action}`);
        lines.push(`                        break;`);
    }

    return lines.join('\n');
}

export async function generateWithOptions(
    dfa: DFA,
    spec: LexSpec,
    outputFile: string,
    options: Partial<GenerateOptions>
): Promise<void> {
    const opts = { ...DEFAULT_OPTIONS, ...options };
    const code = generateToString(dfa, spec);
    const { writeFile } = await import('fs/promises');
    await writeFile(outputFile, code);
}
